Documentation Updates
nautobot/nautobot-plugin-circuit-maintenance pull request #227
Opened 2022-11-14 13:34 UTC by cmsirbu

## What's changed

- Moved existing documentation into a new structure to prepare for the mkdocs rendered docsite.
- Edited and improved the visuals in various places using new syntax from the [Material for Mkdocs theme](https://squidfunk.github.io/mkdocs-material/reference/).
- Added dependencies to poetry environment for development.
- Added configuration for building and hosting the docsite on RTD.
- Replaced the project README with a standardized one. Note: the README will have certain links/images broken until the PR is merged into `develop`.
- Added `invoke docs` task to aid serving docs locally in the dev environment.
- Added test to check that RTD used `docs/requirements.txt` are in sync with dependencies in `pyproject.toml`.

## Building docs

You can build the docs locally in the poetry environment:

```
poetry install
poetry run mkdocs serve
```

See below notes on development environment (more specifically the docker based one).

## TODO

Some sections throughout the files listed below require input (or removal if not applicable to this plugin). All `Developer Note` comments should be resolved and removed.
- [ ] user/app_overview.md
- [ ] user/app_use_cases.md - you might want to add more screenshots
- [ ] user/app_getting_started.md
- [ ] user/faq.md
- [ ] user/external_interactions.md
- [ ] admin/install.md - review
- [ ] admin/upgrade.md
- [ ] admin/uninstall.md
- [ ] admin/compatiblity_matrix.md
- [ ] admin/release_notes - I think the CHANGELOG content should be linking to the docs section release notes, but will leave this decision up to you.
- [ ] dev/extending.md - review
- [ ] dev/contributing.md
- [ ] dev/dev_environment.md - boilerplate guide based on cookie template (old GETTING_STARTED guide). A sync to the cookie dev environment would be beneficial to ensure instructions are accurate.
- [ ] dev/code_reference - check examples provided and add any module/package auto-generated docs that are relevant
- [ ] README.md - review

2023-02-03 17:02 UTC, chadell requested changes

2023-02-03 17:02 UTC, chadell commented on docs/user/app_getting_started.md
> +!!! warning "Developer Note - Remove Me!"
@scetron "Remove Me", also below

2023-02-03 17:02 UTC, chadell commented on docs/user/app_use_cases.md
> +### Configure Notification Sources in `nautobot_config.py`
this to me looks more like "getting started"

2023-02-03 17:02 UTC, chadell commented on docs/user/external_interactions.md
> +# External Interactions
maybe the notification source should come here? those are external integrations

2023-02-03 17:55 UTC, cmsirbu commented
You can see the docs as-built from this branch live here: https://docs.nautobot.com/projects/circuit-maintenance/en/latest/

There are some leftover developer notes in the README.md - you might want to run something like `rgrep -i "developer note"` on the repo to catch'em all.

Note: the logo in the README will be broken until this is merged.

2023-03-13 11:30 UTC, chadell approved these changes
LGTM

2023-03-13 11:31 UTC, merged