Changed extends 'base.html' to extends 'generic/object_detail.html' for detail templates
nautobot/nautobot-plugin-circuit-maintenance pull request #232
Opened 2022-12-31 14:30 UTC by briddo

Fixes: #231

2023-01-02 13:58 UTC, glennmatthews requested changes

2023-01-02 13:58 UTC, glennmatthews commented on .idea/.gitignore
> +# Default ignored files
Need to add `.idea` to the project's base `.gitignore` and remove all of these files from Git.

2023-01-02 13:58 UTC, glennmatthews commented on nautobot_circuit_maintenance/templates/nautobot_circuit_maintenance/circuitimpact.html
> +{% extends 'generic/object_detail.html' %}
`object_detail.html` was only added in Nautobot 1.2 so this change will need to be accompanied by an increase in the project's required Nautobot min_version.

2023-01-23 21:52 UTC, glennmatthews requested changes

2023-01-23 21:52 UTC, glennmatthews commented on nautobot_circuit_maintenance/templates/nautobot_circuit_maintenance/circuitimpact.html
> +{% extends 'generic/object_detail.html' %}
In addition to this change, need to review whether any or all of the contents of `block title` and` `block header` are now redundant, and if they can be removed to simplify the template.

Additionally, `block content` should be updated to only override `block content_left_page` as appropriate.

Same comment on the other template files below.

2023-01-27 18:26 UTC, glennmatthews commented
Looks like there's something incorrect in the `parsednotification.html` that's causing template rendering to error out in the tests.

2023-01-27 22:53 UTC, gsnider2195 commented
> Looks like there's something incorrect in the `parsednotification.html` that's causing template rendering to error out in the tests.

There was a bug in 1.2 that was fixed in https://github.com/nautobot/nautobot/pull/1366 that we're running into here because `ParsedNotification` doesn't have a list view. We'll have to override the header block in that file or create a list view for `ParsedNotification`.

2023-01-30 14:23 UTC, glennmatthews approved these changes

2023-01-31 09:27 UTC, chadell commented
@glennmatthews have you verified to rendered outcome? if so, it LGTM

2023-01-31 14:06 UTC, glennmatthews commented
Locally the only data I have is some configured Notification Sources; that detail view looks fine to me. I don't have data for the other models so I can't verify them manually at this time. The diffs *look* good to me though and the tests are passing so that would catch any egregious template-rendering errors.

2023-02-03 18:00 UTC, merged